### PR TITLE
Switch to custom wlroots/libwayland bindings

### LINKED ISSUE #18: Build fails on musl based systems
```
./zig-cache/o/lLwaO1ZvYa5hBuplK9Yu4M1VOyALWCVjxTPNh2mP5Civhg28EzQVimsSKAc5GFDg/cimport.zig:5738:5: error: opaque types have unknown size and therefore cannot be directly embedded in structs
    last_event: struct_timespec,
    ^
./zig-cache/o/lLwaO1ZvYa5hBuplK9Yu4M1VOyALWCVjxTPNh2mP5Civhg28EzQVimsSKAc5GFDg/cimport.zig:6516:5: note: while checking this field
    seat: [*c]struct_wlr_seat,
    ^
./zig-cache/o/lLwaO1ZvYa5hBuplK9Yu4M1VOyALWCVjxTPNh2mP5Civhg28EzQVimsSKAc5GFDg/cimport.zig:6476:5: note: while checking this field
    popup: [*c]struct_wlr_xdg_popup,
    ^
./zig-cache/o/lLwaO1ZvYa5hBuplK9Yu4M1VOyALWCVjxTPNh2mP5Civhg28EzQVimsSKAc5GFDg/cimport.zig:6493:5: note: while checking this field
    unnamed_161: union_unnamed_162,
    ^
./zig-cache/o/lLwaO1ZvYa5hBuplK9Yu4M1VOyALWCVjxTPNh2mP5Civhg28EzQVimsSKAc5GFDg/cimport.zig:6617:5: note: while checking this field
    surface: [*c]struct_wlr_xdg_surface,
    ^
./src/decoration.zig:11:5: note: while checking this field
    wlr_xdg_toplevel_decoration: *c.wlr_xdg_toplevel_decoration_v1,
    ^
/usr/lib/zig/std/linked_list.zig:22:13: note: while checking this field
            data: T,
            ^
/usr/lib/zig/std/linked_list.zig:52:9: note: while checking this field
        first: ?*Node,
        ^
./src/decoration_manager.zig:14:5: note: while checking this field
    decorations: std.SinglyLinkedList(Decoration),
    ^
./src/server.zig:27:5: note: while checking this field
    decoration_manager: DecorationManager,
    ^
./src/main.zig:13:26: note: referenced here
    var server: Server = undefined;
                         ^
river...The following command exited with error code 1:
/usr/bin/zig build-exe /root/river/src/main.zig --c-source -std=c99 /root/river/include/bindings.c --library c --library wayland-server --library wlroots --library xkbcommon --cache-dir /root/river/zig-cache --name river -target x86_64-linux-musl -I /root/river/protocol -I /root/river -I /usr/include -I /usr/include/libdrm -I /usr/include/pixman-1 -I /usr/include/elogind --cache on 

Build failed. The following command failed:
/root/river/zig-cache/o/3ycZuz4w9FPFWUv5IEQkCiCh7aamLMMWOpfPulKCPUqfJIj4VYEaYed9tOqnRpQJ/build /usr/bin/zig /root/river /root/river/zig-cache -Dtarget=x86_64-linux-musl
```

### LINKED ISSUE #105: Doesn't build on aarch64
Hi! I'm trying to build this on NixOS. I've added `libevdev` to the shell.nix in the Wiki since it was apparently missing, but now I'm getting this error:

```
[nix-shell:~/river]$ zig build -Drelease-safe=true --prefix ./out install
Semantic Analysis [604/865] ./zig-cache/o/_ZROy3lqpPYwM0LfP0uL18zTXufkaKMtOhlQ3QwciuigoSLQKwVO7KO_vPoCin0U/cimport.zig:1288:21: error: use of undeclared identifier '__builtin_va_list'
pub const va_list = __builtin_va_list;
                    ^
./zig-cache/o/_ZROy3lqpPYwM0LfP0uL18zTXufkaKMtOhlQ3QwciuigoSLQKwVO7KO_vPoCin0U/cimport.zig:6511:72: note: referenced here
pub const wlr_log_func_t = ?fn (enum_wlr_log_importance, [*c]const u8, va_list) callconv(.C) void;
                                                                       ^
./zig-cache/o/_ZROy3lqpPYwM0LfP0uL18zTXufkaKMtOhlQ3QwciuigoSLQKwVO7KO_vPoCin0U/cimport.zig:6512:74: note: referenced here
pub extern fn wlr_log_init(verbosity: enum_wlr_log_importance, callback: wlr_log_func_t) void;
                                                                         ^
./river/main.zig:68:6: note: referenced here
    c.wlr_log_init(.WLR_ERROR, null);
     ^
river...The following command exited with error code 1:
/nix/store/mgsj3c99v76q1xypjy2dxg7p97cvcz62-zig-0.6.0/bin/zig build-exe /home/malte/river/river/main.zig --c-source -std=c99 /home/malte/river/protocol/river-control-unstable-v1-protocol.c --c-source -std=c99 /home/malte/river/protocol/river-status-unstable-v1-protocol.c --c-source -std=c99 /home/malte/river/include/bindings.c --library c --library evdev --library pixman-1 --library wayland-server --library wlroots --library xkbcommon --pkg-begin build_options /home/malte/river/zig-cache/river_build_options.zig --pkg-end --release-safe --cache-dir /home/malte/river/zig-cache --name river -I /home/malte/river/protocol -I /home/malte/river -I /nix/store/rwd7kxy9jmn8c6w47ynmysrjay122rbv-libevdev-1.9.1/include/libevdev-1.0 -I /nix/store/xa6x1k3l1il4jqwqp54s6k20fmshfbw8-pixman-0.38.4/include/pixman-1 -I /nix/store/xx0hqxvpvxr9xvp2ybyv5p20jd4hn4zn-wayland-1.18.0/include -I /nix/store/w1l37yr22x7p099fahw50wyna8f9cl59-wlroots-0.11.0/include -I /nix/store/q1iarvdn7r04jg1lvvcp2kfjd2244nlr-libxkbcommon-0.10.0-dev/include -L /nix/store/rwd7kxy9jmn8c6w47ynmysrjay122rbv-libevdev-1.9.1/lib -L /nix/store/xa6x1k3l1il4jqwqp54s6k20fmshfbw8-pixman-0.38.4/lib -L /nix/store/xx0hqxvpvxr9xvp2ybyv5p20jd4hn4zn-wayland-1.18.0/lib -L /nix/store/w1l37yr22x7p099fahw50wyna8f9cl59-wlroots-0.11.0/lib -L /nix/store/fgxq3nrj5gf6ga0mbdjw0lbbwmhb3xal-libxkbcommon-0.10.0/lib --cache on 

Build failed. The following command failed:
/home/malte/river/zig-cache/o/3-L2BaKBzJ0hlgoBeTPbpF-ApupmSgcONLWrrqEJRP77tPSen9Ak6VRAPq_22sMn/build /nix/store/mgsj3c99v76q1xypjy2dxg7p97cvcz62-zig-0.6.0/bin/zig /home/malte/river /home/malte/river/zig-cache -Drelease-safe=true --prefix ./out install
```

Any idea what could have gone wrong here? Thanks!

### LINKED ISSUE #164: Xwayland crash
Runnning glxdemo from mesa-demos causes river to reproducibly crash.

```
Segmentation fault at address 0x14
/home/travankor/git/river/river/XwaylandView.zig:174:40: 0x23a6c6 in XwaylandView.handleMap (river)
    const has_fixed_size = size_hints.*.min_width != 0 and size_hints.*.min_height != 0 and
```

### PR DESCRIPTION
**Pull request by ifreund**
This is a big step up over `@cImport()` for ergonomics and type safety. Nearly all void pointer casts have been eliminated!

I will likely squash this into a single large commit before merging, don't want to have a whole block of commits that don't compile in the history. 

This is currently blocked on zig `0.7.1` due to a bug fixed by this patch: https://github.com/ziglang/zig/pull/7222.

Any review/testing would be appreciated, I'm bound to have made a mistake somewhere among all these changes.

Closes #105
Closes #164
Closes  #18

### CODE REVIEW

**Comment by voroskoi** [comment]
First I run into this:

```
~/code/river on zig-wlroots via ↯ v0.7.0 ❯ zig build
Semantic Analysis [1472/3148] Assertion failed at ../src/stage1/ir.cpp:13700 in ir_resolve_const_type. This is a bug in the Zig compiler.
Unable to dump stack trace: debug info stripped
river...The following command terminated unexpectedly:
/usr/bin/zig build-exe /home/voroskoi/code/river/river/main.zig --library c --library evdev --library wayland-server --library xkbcommon --library wlroots -cflags -std=c99 -- /home/voroskoi/code/river/deps/zig-wayland/generated/xdg-shell-protocol.c -cflags -std=c99 -- /home/voroskoi/code/river/deps/zig-wayland/generated/river-control-unstable-v1-protocol.c -cflags -std=c99 -- /home/voroskoi/code/river/deps/zig-wayland/generated/river-status-unstable-v1-protocol.c -cflags -std=c99 -- /home/voroskoi/code/river/deps/zig-wayland/generated/wlr-layer-shell-unstable-v1-protocol.c -cflags -std=c99 -- /home/voroskoi/code/river/deps/zig-wayland/generated/wlr-output-power-management-unstable-v1-protocol.c --pkg-begin build_options /home/voroskoi/code/river/zig-cache/river_build_options.zig --pkg-end --cache-dir /home/voroskoi/code/river/zig-cache --name river --pkg-begin wayland /home/voroskoi/code/river/deps/zig-wayland/generated/wayland.zig --pkg-end --pkg-begin xkbcommon /home/voroskoi/code/river/deps/zig-xkbcommon/src/xkbcommon.zig --pkg-end --pkg-begin wlroots /home/voroskoi/code/river/deps/zig-wlroots/src/wlroots.zig --pkg-begin wayland /home/voroskoi/code/river/deps/zig-wayland/generated/wayland.zig --pkg-end --pkg-begin xkbcommon /home/voroskoi/code/river/deps/zig-xkbcommon/src/xkbcommon.zig --pkg-end --pkg-begin pixman /home/voroskoi/code/river/deps/zig-pixman/pixman.zig --pkg-end --pkg-end -I /usr/include/libevdev-1.0 --enable-cache
error: the following build command failed with exit code 6:
/home/voroskoi/code/river/zig-cache/o/64a0e5d0dd777a5f030d18a231b77835/build /usr/bin/zig /home/voroskoi/code/river /home/voroskoi/code/river/zig-cache
```

Then I downloaded the latest master (`zig-linux-x86_64-0.7.0+abc729a5f`) build, which worked without the mentioned zig change. I can not start it yet because some libseat error, but I do not think that is related.

Thanks,

**Comment by voroskoi** [comment]
So the libseat part is solved by adding myself to _seatd group. Now I got this:

```
info: (server) initializing
info: (server) Starting without startup command
00:00:00.000 [INFO] [backend/session/libseat.c:128] Successfully loaded libseat session
00:00:00.001 [INFO] [backend/backend.c:157] Found 1 GPUs
00:00:00.001 [INFO] [backend/drm/backend.c:138] Initializing DRM backend for /dev/dri/card0 (i915)
00:00:00.001 [DEBUG] [backend/drm/drm.c:70] Using atomic DRM interface
00:00:00.001 [INFO] [backend/drm/drm.c:255] Found 3 DRM CRTCs
00:00:00.001 [INFO] [backend/drm/drm.c:176] Found 9 DRM planes
Segmentation fault at address 0x0
???:?:?: 0x7fcc6d396a52 in ??? (???)
```

**Comment by voroskoi** [comment]
Here is the gdb bt output:

<details>

```
Starting program: /home/voroskoi/code/river/zig-cache/bin/river
info: (server) initializing
info: (server) Starting without startup command
00:00:00.000 [backend/wayland/backend.c:253] Creating wayland backend
00:00:00.000 [backend/wayland/backend.c:100] Remote wayland global: wl_shm v1
00:00:00.000 [backend/wayland/backend.c:100] Remote wayland global: wl_drm v2
00:00:00.000 [backend/wayland/backend.c:100] Remote wayland global: zwp_linux_dmabuf_v1 v3
00:00:00.000 [backend/wayland/backend.c:100] Remote wayland global: wl_compositor v4
00:00:00.000 [backend/wayland/backend.c:100] Remote wayland global: wl_subcompositor v1
00:00:00.000 [backend/wayland/backend.c:100] Remote wayland global: wl_data_device_manager v3
00:00:00.000 [backend/wayland/backend.c:100] Remote wayland global: zwlr_gamma_control_manager_v1 v1
00:00:00.000 [backend/wayland/backend.c:100] Remote wayland global: gtk_primary_selection_device_manager v1
00:00:00.000 [backend/wayland/backend.c:100] Remote wayland global: zxdg_output_manager_v1 v3
00:00:00.000 [backend/wayland/backend.c:100] Remote wayland global: org_kde_kwin_idle v1
00:00:00.000 [backend/wayland/backend.c:100] Remote wayland global: zwp_idle_inhibit_manager_v1 v1
00:00:00.000 [backend/wayland/backend.c:100] Remote wayland global: zwlr_layer_shell_v1 v2
00:00:00.000 [backend/wayland/backend.c:100] Remote wayland global: xdg_wm_base v2
00:00:00.000 [backend/wayland/backend.c:100] Remote wayland global: zwp_tablet_manager_v2 v1
00:00:00.000 [backend/wayland/backend.c:100] Remote wayland global: org_kde_kwin_server_decoration_manager v1
00:00:00.000 [backend/wayland/backend.c:100] Remote wayland global: zxdg_decoration_manager_v1 v1
00:00:00.000 [backend/wayland/backend.c:100] Remote wayland global: zwp_relative_pointer_manager_v1 v1
00:00:00.000 [backend/wayland/backend.c:100] Remote wayland global: zwp_pointer_constraints_v1 v1
00:00:00.000 [backend/wayland/backend.c:100] Remote wayland global: wp_presentation v1
00:00:00.000 [backend/wayland/backend.c:100] Remote wayland global: zwlr_output_manager_v1 v2
00:00:00.000 [backend/wayland/backend.c:100] Remote wayland global: zwlr_output_power_manager_v1 v1
00:00:00.000 [backend/wayland/backend.c:100] Remote wayland global: zwp_input_method_manager_v2 v1
00:00:00.000 [backend/wayland/backend.c:100] Remote wayland global: zwp_text_input_manager_v3 v1
00:00:00.000 [backend/wayland/backend.c:100] Remote wayland global: zwlr_foreign_toplevel_manager_v1 v3
00:00:00.000 [backend/wayland/backend.c:100] Remote wayland global: zwlr_export_dmabuf_manager_v1 v1
00:00:00.000 [backend/wayland/backend.c:100] Remote wayland global: zwlr_screencopy_manager_v1 v3
00:00:00.000 [backend/wayland/backend.c:100] Remote wayland global: zwlr_data_control_manager_v1 v2
00:00:00.000 [backend/wayland/backend.c:100] Remote wayland global: zwp_primary_selection_device_manager_v1 v1
00:00:00.000 [backend/wayland/backend.c:100] Remote wayland global: wp_viewporter v1
00:00:00.000 [backend/wayland/backend.c:100] Remote wayland global: zwp_virtual_keyboard_manager_v1 v1
00:00:00.000 [backend/wayland/backend.c:100] Remote wayland global: zwlr_virtual_pointer_manager_v1 v2
00:00:00.000 [backend/wayland/backend.c:100] Remote wayland global: zwlr_input_inhibit_manager_v1 v1
00:00:00.000 [backend/wayland/backend.c:100] Remote wayland global: zwp_keyboard_shortcuts_inhibit_manager_v1 v1
00:00:00.000 [backend/wayland/backend.c:100] Remote wayland global: wl_seat v7
00:00:00.000 [backend/wayland/backend.c:100] Remote wayland global: zwp_pointer_gestures_v1 v1
00:00:00.000 [backend/wayland/backend.c:100] Remote wayland global: wl_output v3

Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00007ffff7634373 in __glDispatchCheckMultithreaded () from /lib64/libGLdispatch.so.0
#2  0x00007ffff7e0cd3e in ?? () from /lib64/libEGL.so.1
#3  0x00007ffff7e0e2e9 in eglQueryString () from /lib64/libEGL.so.1
#4  0x00007ffff7e99c62 in wlr_egl_init () from /lib64/libwlroots.so.7
#5  0x00007ffff7e9aac6 in wlr_renderer_autocreate () from /lib64/libwlroots.so.7
#6  0x00007ffff7e91387 in wlr_wl_backend_create () from /lib64/libwlroots.so.7
#7  0x00007ffff7e9d47e in ?? () from /lib64/libwlroots.so.7
#8  0x00007ffff7e9d876 in wlr_backend_autocreate () from /lib64/libwlroots.so.7
#9  0x0000000000226372 in .wlroots.backend.Backend.autocreate (server=0x7ffff7310050, create_renderer_func=0x0) at /home/voroskoi/code/river/deps/zig-wlroots/src/backend.zig:20
#10 0x000000000022064b in Server.init (self=0x7fffffffe238) at Server.zig:80
#11 0x000000000021ee6c in main () at main.zig:117
#12 0x0000000000221ec2 in std.start.callMain () at /home/voroskoi/code/zig/zig-linux-x86_64-0.7.0+abc729a5f/lib/zig/std/start.zig:344
#13 std.start.initEventLoopAndCallMain () at /home/voroskoi/code/zig/zig-linux-x86_64-0.7.0+abc729a5f/lib/zig/std/start.zig:286
#14 std.start.callMainWithArgs (argc=1, argv=0x7fffffffe898, envp=...) at /home/voroskoi/code/zig/zig-linux-x86_64-0.7.0+abc729a5f/lib/zig/std/start.zig:249
#15 std.start.main (c_argc=1, c_argv=0x7fffffffe898, c_envp=0x7fffffffe8a8) at /home/voroskoi/code/zig/zig-linux-x86_64-0.7.0+abc729a5f/lib/zig/std/start.zig:256
(
```

</details>

**Comment by ifreund** [comment]
@voroskoi Thanks for the backtrace and logs, looks like I'll probably need to get a musl machine setup to debug this further.

**Comment by voroskoi** [comment]
OK, take Your time! Just let me know if I can test something for You.

**Comment by maringuu** [comment]
I also get the crash on musl.
`bt full`: https://paste.sr.ht/~maringuu/999f956dd584bfc05908e07fb306d004d8388f28
`bt`: https://paste.sr.ht/~maringuu/f3490c9f78b6b541b3ca3071487c8961c291df4a

**Comment by ifreund** [comment]
River working on musl is blocked by: https://github.com/ziglang/zig/issues/5364. I'm going to try and implement this feature for zig before 0.7.1.

**Comment by ifreund** [comment]
I've now successfully built and run river on musl with my zig patch here: https://github.com/ziglang/zig/pull/7406

**Comment by ifreund** [comment]
zig 0.7.1 has been released! https://ziglang.org/download/0.7.1/release-notes.html

**Pull request merged**
