### PR TITLE
river: always render floating views above layout views

### PR DESCRIPTION
**Pull request by ifreund**
This is a bit of an experiment, I'm not sure if I prefer this behavior in all cases yet but it does significantly help UX in some situations IMO (e.g. file dialogs and other such popups).

### CODE REVIEW

**Comment by YerinAlexey** [comment]
It works but I would prefer to have this as an option (or even better, as a filer) because in my typical workflows I use floating windows as a "scratchpad" to say, put the terminal away when watching videos in mpv

**Comment by ifreund** [comment]
> It works but I would prefer to have this as an option (or even better, as a filter) because in my typical workflows I use floating windows as a "scratchpad" to say, put the terminal away when watching videos in mpv

I'd recommend putting that terminal on a separate tag and toggling focus of that tag.

**Comment by Leon-Plickat** [comment]
I prefer the current behavior, but this works.

Although maybe we can just stick floating pop-ups on top of their parent views.

**Comment by ifreund** [comment]
> Although maybe we can just stick floating pop-ups on top of their parent views.

This would be significantly more complicated to implement, and still wouldn't solve this issue for all popups. Take for example the gtk pinentry popup commonly used for gpg2 which has no parent.

I've been running with this PR for 4 days now apparently and have yet to hit a case where I felt that the UX was worse than the status quo, I think I'll keep testing it for a few more days then merge this if nothing comes up.

**Pull request merged**
