### PR TITLE
command: Use std.ComptimeStringMap to get impl. function from command string

### PR DESCRIPTION
**Pull request by Leon-Plickat**
The `// TODO` told me to do it.

Looks cleaner, but for the low amount of strings the performance improvement is probably not measurable.

### CODE REVIEW

**Review by ifreund — APPROVED** [review]
LGTM, just needs conflicts resolved.

**Comment by ifreund** [comment]
And yeah, this is more about cleanliness than performance.

**Comment by Leon-Plickat** [comment]
Rebased against master, should be good now.

**Review by ifreund — APPROVED** [review]
LGTM, Thanks!

**Pull request merged**
