### PR TITLE
Implement wlr-output-power-management-unstable-v1 protocol

### PR DESCRIPTION
**Pull request by maringuu**
This is my first protocol implementation of any kind.

I need help with one little thing which is that when disabling and enabling afterwards I get an error.
Can you point me to anything I should investigate?
```
info: (server) initializing
debug: (server) new output eDP-1
debug: (server) new output DP-1
info: (server) running...
debug: (server) new xdg_toplevel
debug: (server) view 'Alacritty' mapped
debug: (transaction) started transaction with 1 pending configure(s)
debug: (server) Disabling dmps for output eDP-1
00:00:08.531 [ERROR] [types/wlr_output.c:567] Basic output test failed
debug: (server) Enabling dmps for output eDP-1
info: (server) shutting down
debug: (server) output 'eDP-1' destroyed
debug: (server) output 'DP-1' destroyed
```

For reference here is sways code: https://github.com/swaywm/sway/blob/0cb9282aeebddeed0b5259f153f98a45311053a5/sway/desktop/output.c#L1036

For testing I hacked together a little wayland client which will turn off the first output it finds and will turn it back on three seconds later. https://git.sr.ht/~maringuu/wlr-dpms

Edit: It seems that I "try to commit a buffer to a disabled output"

### CODE REVIEW

**Comment by ifreund** [comment]
Haven't taken a close look at this, but perhaps we now need a check if the output is enabled in the frame handler? You could use gdb and run river in a nested session to see which `wlr_output_commit` call is causing this error.

**Comment by maringuu** [comment]
Thanks for your input!
It seems like you are right and we need a check whether the output is enabled in the frame handler. I just tested it and the error dissapears.
Also I found out that debugging in a nested session is useless because a wayland output can't be disabled.
Debugging a session that renders to drm is not usefull either because no frame events should be send. But also I can't attach gdb to river because I use alpine and gcompat.


The commit that fails is the one in the `render.zig`. The commit in `handleOutputPowerManagement` succeeds.
According to the wlroots docs an disabled output will not send frame events.
What I don't understand is why a frame event is send after disabling the output succeeded and was commited.

I'll investigate further the next days when I have time.

**Comment by maringuu** [comment]
I am now convinced that this is a wlroots bug.
The check in `handleFrame` should not have to be there since no frame events should be send when the output is disabled.

I opened a PR at wlroots to fix this.
https://github.com/swaywm/wlroots/pull/2456

**Comment by maringuu** [comment]
The wlroots bug is fixed now.
I guess we'll wait for the next wlroots release then.

**Comment by ifreund** [comment]
The next wlroots release should come in the next week or two based on when wayfire is ready, so waiting for that would be reasonable. We could also add the check that will be made unnecessary by that release with a `TODO(wlroots): ...` comment to be removed upon updating.

Nice work finding and fixing the issue in wlroots!

**Comment by maringuu** [comment]
> We could also add the check that will be made unnecessary by that release with a `TODO(wlroots): ...` comment to be removed upon updating.

Good idea! Pushed it just now and also rebased.

> Nice work finding and fixing the issue in wlroots!

Thanks!

**Review by ifreund — APPROVED** [review]
LGTM, Thanks!

**Comment by Leon-Plickat** [comment]
@dkwo something like this: https://sr.ht/~leon_plickat/wlopm/

**Comment by dkwo** [comment]
@Leon-Plickat Is there a way to do DPMS (ie. blank the screen but keep workspaces as-is), other than turn off output?
See also #571

**Comment by Leon-Plickat** [comment]
@dkwo Yes, using the tool I linked to. It will turn off the output, not destroy it.

**Comment by dkwo** [comment]
Just to make sure I understand:
is this tool working differently than wlr-randr, which I'm currently using?

**Comment by dkwo** [comment]
@Leon-Plickat Thanks, indeed it works, where `wlr-randr` was not working!
I wrote a template to build this on Void linux, does it look fine to you?
(Perhaps at some point tag a release, so one could package it there :)
```
# Template file for 'wlopm'
pkgname=wlopm
version=git20220318
revision=1
_commit=27b7ccd1f1f2f5f2986508890805934c3e7614ee
wrksrc=${pkgname}-${_commit}
build_style=gnu-makefile
makedepends="wayland-devel"
short_desc="Wayland output power management"
maintainer="dkwo ..."
license="GPL-3.0-or-later"
homepage="https://git.sr.ht/~leon_plickat/wlopm"
distfiles="https://git.sr.ht/~leon_plickat/${pkgname}/archive/${_commit}.tar.gz"
checksum=3f96c7382e2aaa4d5fdcdec12a2ad81eb623915dd8207a9b2d614a644c0815d1
make_check=no # No test suite
```

**Comment by dkwo** [comment]
@Leon-Plickat Btw, it would be nice to have both options in the same tool: right now i'm using wlr-randr if I need to destroy the output (e.g. in a multi-monitor setup, where I don't want the laptop monitor), and wlopm if I want to preserve it (e.g. in the same setup, to do dpms/turn off screen).

**Pull request merged**
