### PR TITLE
Warp cursor on output change

### LINKED ISSUE #178: Move cursor to new output automatically on focus-output command
The focus should follow the cursor and the cursor should follow the output.

ex. If I move my cursor to another monitor and have focus_follows_cursor set to normal, the window my mouse is hovering over should be focused. I shouldn't have to manually switch output to focus it.

ex. If I switch outputs, my mouse should (at least have the option) be repositioned to the chosen output.

### PR DESCRIPTION
**Pull request by Leon-Plickat**
On output change, if the cursor is not already on the newly focused output, it
will now be warped to its center. The check is necessary, since focusing outputs
with the pointer will be implemented in the future.

---

Matches the behaviour of Sway and pretty much every other desktop.

closes #178

### CODE REVIEW

**Review by YerinAlexey — APPROVED** [review]

**Review by aRkar-KyAw — APPROVED** [review]

**Comment by aruhier** [comment]
Can it be a config option?

Indeed it matches every other desktop, but it's usually configurable.

**Comment by Leon-Plickat** [comment]
I don't see why anyone would ever turn this off.

**Comment by aruhier** [comment]
I do on multiple screen, on bspwm.

Example: I have 3 screens, and one of the screen always shows an IRC window. If my cursor is on Firefox on my main screen, and an IRC windows is on the screen on the right, I can quickly answer to someone by switching to this screen, and continue what I was doing without resetting my cursor position.

**Comment by ifreund** [comment]
Needs a rebase since your other PR was merged.

**Review by ifreund — APPROVED** [review]
Thanks!

**Pull request merged**
