### PR TITLE
Update contrib/layout.c to river-layout-v3

### PR DESCRIPTION
**Pull request by Leon-Plickat**

### CODE REVIEW

**Comment by HeavyRain266** [comment]
What about adding example Makefile to teach people how to use wayland-scanner with `river-layout-v2.xml `? This is really clean and documented code but exanple of generating header `river-layout-v2.h` would be really helpful.

**Comment by Leon-Plickat** [comment]
FWIW I develop `layout.c` out-of-tree [here](https://git.sr.ht/~leon_plickat/rilay) where I also have a Makefile set up.

**Comment by HeavyRain266** [comment]
Thanks for explaination :)

**Review by ifreund — APPROVED** [review]
LGTM, thanks. I fixed one typo in a comment myself and seem to have pulled your commit into my branch in a way github doesn't recognize as a merge, so this PR sadly won't turn purple :D

**Pull request closed without merging**
